
package org.tusiri.ws.answer;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Answer", targetNamespace = "http://answer.ws.tusiri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Answer {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.tusiri.ws.answer.AnswerItem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAnswerList", targetNamespace = "http://answer.ws.tusiri.org/", className = "org.tusiri.ws.answer.GetAnswerList")
    @ResponseWrapper(localName = "getAnswerListResponse", targetNamespace = "http://answer.ws.tusiri.org/", className = "org.tusiri.ws.answer.GetAnswerListResponse")
    @Action(input = "http://answer.ws.tusiri.org/Answer/getAnswerListRequest", output = "http://answer.ws.tusiri.org/Answer/getAnswerListResponse")
    public List<AnswerItem> getAnswerList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws IOException_Exception
     * @throws ParseException_Exception
     * @throws ClientProtocolException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAnswer", targetNamespace = "http://answer.ws.tusiri.org/", className = "org.tusiri.ws.answer.CreateAnswer")
    @ResponseWrapper(localName = "createAnswerResponse", targetNamespace = "http://answer.ws.tusiri.org/", className = "org.tusiri.ws.answer.CreateAnswerResponse")
    @Action(input = "http://answer.ws.tusiri.org/Answer/createAnswerRequest", output = "http://answer.ws.tusiri.org/Answer/createAnswerResponse", fault = {
        @FaultAction(className = ClientProtocolException_Exception.class, value = "http://answer.ws.tusiri.org/Answer/createAnswer/Fault/ClientProtocolException"),
        @FaultAction(className = IOException_Exception.class, value = "http://answer.ws.tusiri.org/Answer/createAnswer/Fault/IOException"),
        @FaultAction(className = ParseException_Exception.class, value = "http://answer.ws.tusiri.org/Answer/createAnswer/Fault/ParseException")
    })
    public int createAnswer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws ClientProtocolException_Exception, IOException_Exception, ParseException_Exception
    ;

}
