
package org.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IdentityImplService", targetNamespace = "http://jaxws.org/", wsdlLocation = "http://localhost:8002/ws/stackexchange?wsdl")
public class IdentityImplService
    extends Service
{

    private final static URL IDENTITYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IDENTITYIMPLSERVICE_EXCEPTION;
    private final static QName IDENTITYIMPLSERVICE_QNAME = new QName("http://jaxws.org/", "IdentityImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8002/ws/stackexchange?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IDENTITYIMPLSERVICE_WSDL_LOCATION = url;
        IDENTITYIMPLSERVICE_EXCEPTION = e;
    }

    public IdentityImplService() {
        super(__getWsdlLocation(), IDENTITYIMPLSERVICE_QNAME);
    }

    public IdentityImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IDENTITYIMPLSERVICE_QNAME, features);
    }

    public IdentityImplService(URL wsdlLocation) {
        super(wsdlLocation, IDENTITYIMPLSERVICE_QNAME);
    }

    public IdentityImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IDENTITYIMPLSERVICE_QNAME, features);
    }

    public IdentityImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IdentityImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Identity
     */
    @WebEndpoint(name = "IdentityImplPort")
    public Identity getIdentityImplPort() {
        return super.getPort(new QName("http://jaxws.org/", "IdentityImplPort"), Identity.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Identity
     */
    @WebEndpoint(name = "IdentityImplPort")
    public Identity getIdentityImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.org/", "IdentityImplPort"), Identity.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IDENTITYIMPLSERVICE_EXCEPTION!= null) {
            throw IDENTITYIMPLSERVICE_EXCEPTION;
        }
        return IDENTITYIMPLSERVICE_WSDL_LOCATION;
    }

}
