
package org.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Identity", targetNamespace = "http://jaxws.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Identity {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://jaxws.org/Identity/createTokenRequest", output = "http://jaxws.org/Identity/createTokenResponse")
    public String createToken(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://jaxws.org/Identity/whoIsRequest", output = "http://jaxws.org/Identity/whoIsResponse")
    public String whoIs(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
