/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package service;

import connection.DB;
import java.sql.Connection;
import org.json.*;
import java.io.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;
import javax.servlet.*;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author Fitra Rahmamuliani
 */

@WebServlet(urlPatterns = "/login")
public class login extends HttpServlet {
    private static final long serialVersionUID = 1;
    /* Connect to database */
    Connection conn = DB.connect();
    
    /* Make JSON object */
    JSONObject jo = new JSONObject();
    
    public login(){
        super();
        /* to do autogenerated contructor stub*/
    }
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
    {
        doPost(request, response);
    }
    
   protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException 
   { 
       String email = request.getParameter("email"); 
       String pass = request.getParameter("password"); 
       response.setContentType("text/html"); 
       PrintWriter out = response.getWriter(); 
       RequestDispatcher rd = null; 
       request.setAttribute(email, "name"); 
              
       /*LOGIN AUTHENTICATION*/
       int user_id = -1;
       try{
            Statement stmt = conn.createStatement();
            String sql = "SELECT user_id FROM user WHERE email="+ email + " AND password=" + pass + ";";
            ResultSet r = stmt.executeQuery(sql);
            user_id = r.getInt("user_id");
       }
       catch (SQLException ex){
        }
       
       if (user_id != -1)
       {
           UUID generateToken = UUID.randomUUID();
           String token = generateToken.toString();
           try{
               Statement stmt = conn.createStatement();
               String sql = "INSERT INTO token (token_id,user_id,token_expired) VALUES (" + token + "," + user_id + ","; 
               /* query di atas belum selesai karena token expirednya belum diatur lagi*/
           }
           catch (SQLException ex){
           }
           String query = "UPDATE user SET token="+ token +" WHERE name=" + email +";";
           rd = request.getRequestDispatcher("/WelcomeServlet"); 
           rd.forward(request, response);
       }
       else{ 
            out.println("<b>Invalid Login Info.</b><br>"); 
            rd = request.getRequestDispatcher("/login.jsp"); 
            rd.include(request, response); } out.close(); 
   }
}
